---
all:
  children:
    wordpress_servers:
      children:
        staging:
          hosts:
            wordpress_server_1:
              ansible_host: 54.167.113.64
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/wordpress_server.pem
        
        production:
          hosts:
            wordpress_server_2:
              ansible_host: 54.167.113.65
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/wordpress_server.pem